Icon conversion: support GraphicsMagick in addition to  ImageMagick (PR #1002)
Co-authored-by: Ronan Jouchet <ronan@jouchet.fr>

diff --git a/icon-scripts/convertToPng b/icon-scripts/convertToPng
--- a/icon-scripts/convertToPng
+++ b/icon-scripts/convertToPng
@@ -8,8 +8,27 @@
 
 set -e
 
-type convert >/dev/null 2>&1 || { echo >&2 "Cannot find required ImageMagick 'convert' executable, please install it and make sure it is in your PATH"; exit 1; }
-type identify >/dev/null 2>&1 || { echo >&2 "Cannot find required ImageMagick 'identify' executable, please install it and make sure it is in your PATH"; exit 1; }
+HAVE_IMAGEMAGICK=
+HAVE_GRAPHICSMAGICK=
+
+type convert &>/dev/null && type identify &>/dev/null && HAVE_IMAGEMAGICK=true
+type gm &>/dev/null && gm version | grep GraphicsMagick &>/dev/null && HAVE_GRAPHICSMAGICK=true
+
+if [[ -z "$HAVE_IMAGEMAGICK" && -z "$HAVE_GRAPHICSMAGICK" ]]; then
+	type convert >/dev/null 2>&1 || echo >&2 "Cannot find required ImageMagick 'convert' executable"
+	type identify >/dev/null 2>&1 || echo >&2 "Cannot find required ImageMagick 'identify' executable"
+	type gm &>/dev/null && gm version | grep GraphicsMagick &>/dev/null && echo >&2 "Cannot find GraphicsMagick"
+	echo >&2 "ImageMagic or GraphicsMagic is required, please ensure they are in your PATH"
+	exit 1
+fi
+
+CONVERT="convert"
+IDENTIFY="identify"
+if [[ -z "$HAVE_IMAGEMAGICK" ]]; then
+	# we must have GraphicsMagick then
+	CONVERT="gm convert"
+	IDENTIFY="gm identify"
+fi
 
 # Parameters
 SOURCE="$1"
@@ -41,9 +60,9 @@ mkdir -p "${TEMP_DIR}"
 
 # check if .ico is a sequence
 # pipe into cat so no exit code is given for grep if no matches are found
-IS_ICO_SET="$(identify "${SOURCE}" | grep -e "\w\.ico\[0" | cat )"
+IS_ICO_SET="$($IDENTIFY "${SOURCE}" | grep -e "\w\.ico\[0" | cat )"
 
-convert "${SOURCE}" "${TEMP_DIR}/${BASE}.png"
+$CONVERT "${SOURCE}" "${TEMP_DIR}/${BASE}.png"
 if [ "${IS_ICO_SET}" ]; then
 	# extract the largest(?) image from the set
     cp "${TEMP_DIR}/${BASE}-0.png" "${DEST}"
