Better error message in convertToPng

diff --git a/icon-scripts/convertToPng b/icon-scripts/convertToPng
--- a/icon-scripts/convertToPng
+++ b/icon-scripts/convertToPng
@@ -15,9 +15,11 @@ type convert &>/dev/null && type identify &>/dev/null && HAVE_IMAGEMAGICK=true
 type gm &>/dev/null && gm version | grep GraphicsMagick &>/dev/null && HAVE_GRAPHICSMAGICK=true
 
 if [[ -z "$HAVE_IMAGEMAGICK" && -z "$HAVE_GRAPHICSMAGICK" ]]; then
-	echo >&2 "Cannot find either ImageMagick or GraphicsMagick"
-	type convert >/dev/null 2>&1 || { echo >&2 "Cannot find required ImageMagick 'convert' executable, please install it and make sure it is in your PATH"; exit 1; }
-	type identify >/dev/null 2>&1 || { echo >&2 "Cannot find required ImageMagick 'identify' executable, please install it and make sure it is in your PATH"; exit 1; }
+	type convert >/dev/null 2>&1 || echo >&2 "Cannot find required ImageMagick 'convert' executable"
+	type identify >/dev/null 2>&1 || echo >&2 "Cannot find required ImageMagick 'identify' executable"
+	type gm &>/dev/null && gm version | grep GraphicsMagick &>/dev/null && echo >&2 "Cannot find GraphicsMagick"
+	echo >&2 "ImageMagic or GraphicsMagic is required, please ensure they are in your PATH"
+	exit 1
 fi
 
 CONVERT="convert"
